### PR TITLE
Fixes typo

### PR DESCRIPTION
**Pull request by antonversal**

### CODE REVIEW

**Comment by tbinna** [comment]
Thanks for the contribution @antonversal. Could you amend the commit message to follow the Angular commit convention: https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary

**Comment by antonversal** [comment]
Hi @tbinna,
I have updated the message.
Do you have plans to support nx v18?

**Comment by tbinna** [comment]
@antonversal apologies, the commit tag should be `docs`. There is a husky commit hook that you can install by running `npm run prepare` which will validate the commit message.

Regarding nx v18, I did not start work on it but don't expect it to be too difficult. I think there is some work required with the project graph integration that changed slightly.

**Comment by tbinna** [comment]
This has been fixed in #56

**Pull request closed without merging**
